### ISSUE TITLE
trash-list does not list trashed files over mount points with python3

### ISSUE THREAD

**Issue by Ambrevar** [andreafrancia/trash-cli#95]
Go to any mount point that is not `/` and trash a file. Now run
`trash-list` and see that this file is missing.
This works fine when python2 is used, it only fails with python3.

**Comment by sukramblak** [comment]
I can confirm this bug!  using Python 3.6.1 on current Arch linux.  Using Python 2.7.13 get's it working again but current trash-cli and python 2.7.13 then leads to trash-put being unusable. It asks for "file to trash" even if it is given ;)

**Comment by evert-mouw** [comment]
Same trash-list problem for me. Python 3.6.3, Arch Linux (64 bit).

**Comment by Kareeeeem** [comment]
ditto

```
~ $ python3 --version; uname -a
Python 3.6.4
Linux kareem 4.14.0-1-amd64 #1 SMP Debian 4.14.2-1 (2017-11-30) x86_64 GNU/Linux
```

**Comment by mlmeola** [comment]
#115 should fix this.

My fix uses `bytes` instead of strings to interact with libc to get the mountpoints and then encodes the results as utf8. Possibly this wouldn't work in systems with non-utf8-compatible encodings or if you have paths without a valid utf8 interpretation, but that would probably break trash-cli anyway.

**Comment by riyad** [comment]
I was trying to find out why `trash-list` seemed to always miss trashes in directories mounted below my `$HOME`.
Dissecting the code in the `list_mount_points` module revealed that `mount_points_from_getmnt()` always returned an empty list and `getmntent()` always returned `NULL`. ☹
I couldn't it figure out why until I stumbled on #115. It seems the fix is really as simple as prefixing the string arguments to `fopen()` with "b". :joy:

**Comment by jaysonlarose** [comment]
Looks like this is still an issue, and the last comment is over a year old...
"Me-too"ing this issue in hopes it gets some visibility.

**Comment by andreafrancia** [comment]
This should have been solved in version 0.20.11.23 with the introduction of the use of `psutil`

**Comment by jaysonlarose** [comment]
Yep, looks fixed to me. Thank you!
